[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.curl",
    "php82Extensions.pdo_mysql",
    "php82Extensions.zip",
    "php82Extensions.xml",
    "php82Extensions.mbstring",
    "php82Extensions.intl",
    "php82Extensions.gd"
]

[phases.install]
cmds = [
    "composer install --no-dev",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}" 