[build]
builder = "nixpacks"
buildCommand = """
  curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
  composer install --no-dev && \
  php artisan config:cache && \
  php artisan route:cache && \
  php artisan view:cache
"""

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never" 